from __future__ import annotations

import datetime as dt
import json
import sys
import types
import wave
from io import BytesIO

from PIL import Image
from youtube_daily_automation import audio
from youtube_daily_automation.cli import main
from youtube_daily_automation.documentary import build_documentary_plan
from youtube_daily_automation.subtitles import write_srt
from youtube_daily_automation.topics import fetch_daily_topics
from youtube_daily_automation.visuals import prepare_scene_visual_assets


def test_documentary_plan_has_scene_prompts_and_narration() -> None:
    topics = fetch_daily_topics(dt.date(2026, 6, 6), offline=True)
    plan = build_documentary_plan(
        topic="The Secret Life of Volcanoes",
        day=dt.date(2026, 6, 6),
        source_topics=topics,
        scene_count=24,
        duration_seconds=420,
        channel_name="Test Channel",
    )

    assert plan.title == "The Secret Life of Volcanoes: The Story Behind the Moment"
    assert len(plan.scenes) == 24
    assert all(scene.image_prompt for scene in plan.scenes)
    assert all(scene.narration for scene in plan.scenes)
    assert sum(scene.duration_seconds for scene in plan.scenes) == 420
    assert "Generated by an automated documentary video pipeline" in plan.description


def test_srt_timestamps_are_generated_per_scene(tmp_path) -> None:
    plan = build_documentary_plan(
        topic="Ocean Mysteries",
        day=dt.date(2026, 6, 6),
        source_topics=fetch_daily_topics(dt.date(2026, 6, 6), offline=True),
        scene_count=3,
        duration_seconds=12,
        channel_name="Test Channel",
    )

    srt_path = write_srt(plan.scenes, tmp_path / "subtitles.srt")
    srt = srt_path.read_text(encoding="utf-8")

    assert "00:00:00,000 --> 00:00:04,000" in srt
    assert "00:00:08,000 --> 00:00:12,000" in srt
    assert srt.count("-->") == 3


def test_cli_dry_run_writes_documentary_assets(tmp_path) -> None:
    exit_code = main(
        [
            "run",
            "--offline",
            "--dry-run",
            "--allow-short-render",
            "--scene-count",
            "3",
            "--duration-seconds",
            "12",
            "--narration-speed",
            "+12%",
            "--music-volume",
            "0.25",
            "--transition-style",
            "slide",
            "--topic",
            "Deep Sea Signals",
            "--date",
            "2026-06-06",
            "--output-dir",
            str(tmp_path),
        ]
    )

    metadata = json.loads((tmp_path / "metadata.json").read_text(encoding="utf-8"))
    prompts = json.loads((tmp_path / "image_prompts.json").read_text(encoding="utf-8"))

    assert exit_code == 0
    assert metadata["scene_count"] == 3
    assert metadata["duration_seconds"] == 12
    assert metadata["dry_run"] is True
    assert metadata["image_provider"] == "wikimedia"
    assert metadata["narration_speed"] == "+12%"
    assert metadata["music_volume"] == 0.25
    assert metadata["transition_style"] == "slide"
    assert len(prompts) == 3
    assert (tmp_path / "subtitles.srt").exists()


def test_visual_assets_fall_back_when_wikimedia_has_no_result(monkeypatch, tmp_path) -> None:
    class EmptyResponse:
        def raise_for_status(self):
            return None

        def json(self):
            return {"query": {"pages": []}}

    monkeypatch.setitem(sys.modules, "requests", types.SimpleNamespace(get=lambda *args, **kwargs: EmptyResponse()))
    plan = build_documentary_plan(
        topic="Ocean Mysteries",
        day=dt.date(2026, 6, 6),
        source_topics=fetch_daily_topics(dt.date(2026, 6, 6), offline=True),
        scene_count=2,
        duration_seconds=8,
        channel_name="Test Channel",
    )

    assets = prepare_scene_visual_assets(
        plan,
        tmp_path / "scene_assets",
        provider="wikimedia",
        allow_fallback=True,
    )

    assert [asset.provider for asset in assets] == ["fallback", "fallback"]
    assert (tmp_path / "scene_assets" / "scene_01.png").exists()
    assert not (tmp_path / "scene_assets" / "wikimedia_scene_01.png").exists()


def test_visual_assets_download_wikimedia_images(monkeypatch, tmp_path) -> None:
    image = Image.new("RGB", (16, 9), color=(25, 50, 75))
    buffer = BytesIO()
    image.save(buffer, format="PNG")
    image_bytes = buffer.getvalue()

    class FakeApiResponse:
        def raise_for_status(self):
            return None

        def json(self):
            return {
                "query": {
                    "pages": [
                        {
                            "title": "File:Ocean.jpg",
                            "imageinfo": [
                                {
                                    "mime": "image/jpeg",
                                    "url": "https://example.test/ocean.png",
                                    "descriptionurl": "https://commons.wikimedia.org/wiki/File:Ocean.jpg",
                                    "extmetadata": {
                                        "LicenseShortName": {"value": "CC BY-SA 4.0"},
                                        "Artist": {"value": "Example Photographer"},
                                    },
                                }
                            ],
                        }
                    ]
                }
            }

    class FakeImageResponse:
        content = image_bytes

        def raise_for_status(self):
            return None

    def fake_get(url, *args, **kwargs):
        if "commons.wikimedia.org" in url:
            return FakeApiResponse()
        return FakeImageResponse()

    monkeypatch.setitem(sys.modules, "requests", types.SimpleNamespace(get=fake_get))
    plan = build_documentary_plan(
        topic="Ocean Mysteries",
        day=dt.date(2026, 6, 6),
        source_topics=fetch_daily_topics(dt.date(2026, 6, 6), offline=True),
        scene_count=1,
        duration_seconds=4,
        channel_name="Test Channel",
    )

    assets = prepare_scene_visual_assets(
        plan,
        tmp_path / "scene_assets",
        provider="wikimedia",
        allow_fallback=False,
    )

    assert assets[0].provider == "wikimedia"
    assert assets[0].path.endswith("wikimedia_scene_01.png")
    assert assets[0].license_name == "CC BY-SA 4.0"
    assert assets[0].image_url == "https://example.test/ocean.png"
    assert (tmp_path / "scene_assets" / "wikimedia_scene_01.png").exists()


def test_visual_assets_fall_back_to_wikipedia_summary(monkeypatch, tmp_path) -> None:
    image = Image.new("RGB", (16, 9), color=(25, 50, 75))
    buffer = BytesIO()
    image.save(buffer, format="PNG")
    image_bytes = buffer.getvalue()

    class EmptyCommonsResponse:
        def raise_for_status(self):
            return None

        def json(self):
            return {"query": {"pages": []}}

    class SummaryResponse:
        status_code = 200

        def raise_for_status(self):
            return None

        def json(self):
            return {
                "title": "Ocean",
                "thumbnail": {"source": "https://example.test/ocean-summary.png"},
                "content_urls": {"desktop": {"page": "https://en.wikipedia.org/wiki/Ocean"}},
            }

    class FakeImageResponse:
        content = image_bytes

        def raise_for_status(self):
            return None

    def fake_get(url, *args, **kwargs):
        if "commons.wikimedia.org" in url:
            return EmptyCommonsResponse()
        if "api/rest_v1/page/summary" in url:
            return SummaryResponse()
        return FakeImageResponse()

    monkeypatch.setitem(sys.modules, "requests", types.SimpleNamespace(get=fake_get))
    plan = build_documentary_plan(
        topic="Ocean mysteries",
        day=dt.date(2026, 6, 6),
        source_topics=fetch_daily_topics(dt.date(2026, 6, 6), offline=True),
        scene_count=1,
        duration_seconds=4,
        channel_name="Test Channel",
    )

    assets = prepare_scene_visual_assets(plan, tmp_path / "scene_assets", provider="wikimedia")

    assert assets[0].provider == "wikipedia"
    assert assets[0].source_url == "https://en.wikipedia.org/wiki/Ocean"
    assert assets[0].image_url == "https://example.test/ocean-summary.png"
    assert (tmp_path / "scene_assets" / "wikipedia_scene_01.png").exists()


def test_visual_assets_cache_downloaded_wikimedia_images(monkeypatch, tmp_path) -> None:
    image = Image.new("RGB", (16, 9), color=(25, 50, 75))
    buffer = BytesIO()
    image.save(buffer, format="PNG")
    image_bytes = buffer.getvalue()
    image_downloads = []

    class FakeApiResponse:
        def raise_for_status(self):
            return None

        def json(self):
            return {
                "query": {
                    "pages": [
                        {
                            "title": "File:Ocean.jpg",
                            "imageinfo": [
                                {
                                    "mime": "image/jpeg",
                                    "thumburl": "https://example.test/ocean-thumb.png",
                                    "url": "https://example.test/ocean.png",
                                    "descriptionurl": "https://commons.wikimedia.org/wiki/File:Ocean.jpg",
                                    "extmetadata": {},
                                }
                            ],
                        }
                    ]
                }
            }

    class FakeImageResponse:
        content = image_bytes

        def raise_for_status(self):
            return None

    def fake_get(url, *args, **kwargs):
        if "commons.wikimedia.org" in url:
            return FakeApiResponse()
        image_downloads.append(url)
        return FakeImageResponse()

    monkeypatch.setitem(sys.modules, "requests", types.SimpleNamespace(get=fake_get))
    plan = build_documentary_plan(
        topic="Ocean Mysteries",
        day=dt.date(2026, 6, 6),
        source_topics=fetch_daily_topics(dt.date(2026, 6, 6), offline=True),
        scene_count=1,
        duration_seconds=4,
        channel_name="Test Channel",
    )

    prepare_scene_visual_assets(plan, tmp_path / "scene_assets", provider="wikimedia")
    prepare_scene_visual_assets(plan, tmp_path / "scene_assets", provider="wikimedia")

    assert image_downloads == ["https://example.test/ocean-thumb.png"]
    assert list((tmp_path / "scene_assets" / "cache").glob("*.png"))


def test_wikimedia_threshold_requires_allow_fallback(monkeypatch, tmp_path) -> None:
    class EmptyResponse:
        status_code = 404

        def raise_for_status(self):
            return None

        def json(self):
            return {"query": {"pages": []}}

    monkeypatch.setitem(sys.modules, "requests", types.SimpleNamespace(get=lambda *args, **kwargs: EmptyResponse()))
    plan = build_documentary_plan(
        topic="Ocean Mysteries",
        day=dt.date(2026, 6, 6),
        source_topics=fetch_daily_topics(dt.date(2026, 6, 6), offline=True),
        scene_count=2,
        duration_seconds=8,
        channel_name="Test Channel",
    )

    try:
        prepare_scene_visual_assets(plan, tmp_path / "scene_assets", provider="wikimedia")
    except RuntimeError as error:
        assert "coverage too low" in str(error)
    else:
        raise AssertionError("Expected low Wikimedia coverage to fail without allow_fallback.")


def test_edge_tts_success_writes_voice_file(monkeypatch, tmp_path) -> None:
    async def edge_tts(text, output_path, **kwargs):
        output_path.write_bytes(b"edge voice")
        return output_path

    monkeypatch.setattr(audio, "synthesize_voice_async", edge_tts)

    output_path = tmp_path / "voice.mp3"
    returned_path = audio.synthesize_documentary_voice(
        "hello",
        output_path,
        provider="edge",
        fallback_duration_seconds=2,
    )

    assert returned_path == output_path
    assert output_path.read_bytes() == b"edge voice"


def test_edge_tts_failure_writes_silent_fallback(monkeypatch, tmp_path) -> None:
    async def fail_edge(*args, **kwargs):
        raise RuntimeError("edge unavailable")

    monkeypatch.setattr(audio, "synthesize_voice_async", fail_edge)
    monkeypatch.setattr(audio.time, "sleep", lambda seconds: None)

    output_path = tmp_path / "voice.mp3"
    fallback_path = tmp_path / "silent_voice.wav"
    returned_path = audio.synthesize_documentary_voice(
        "hello",
        output_path,
        provider="edge",
        fallback_path=fallback_path,
        fallback_duration_seconds=2,
    )

    assert returned_path == fallback_path
    assert not output_path.exists()
    with wave.open(str(fallback_path), "rb") as wav:
        assert wav.getnchannels() == 1
        assert wav.getframerate() == 44_100
        assert wav.getnframes() == 88_200


def test_skip_tts_alias_skips_tts_and_continues_to_render(monkeypatch, tmp_path) -> None:
    render_calls = []

    def fail_if_called(*args, **kwargs):
        raise AssertionError("TTS should not run with --skip-tts")

    def fake_music(path, *, duration_seconds, volume=0.14):
        path.write_bytes(b"fake music")
        return path

    def fake_render(*args, **kwargs):
        render_calls.append(kwargs)
        kwargs["output_path"].write_bytes(b"fake video")
        return kwargs["output_path"]

    def fake_visual_assets(plan, assets_dir, *, provider, allow_fallback):
        assets_dir.mkdir(parents=True, exist_ok=True)
        return [
            types.SimpleNamespace(path=str(assets_dir / f"scene_{scene.number:02d}.png"), to_dict=lambda scene=scene: {"scene_number": scene.number})
            for scene in plan.scenes
        ]

    monkeypatch.setattr("youtube_daily_automation.cli.synthesize_documentary_voice", fail_if_called)
    monkeypatch.setattr("youtube_daily_automation.cli.generate_background_music", fake_music)
    monkeypatch.setattr("youtube_daily_automation.cli.prepare_scene_visual_assets", fake_visual_assets)
    monkeypatch.setitem(
        sys.modules,
        "youtube_daily_automation.video",
        types.SimpleNamespace(render_documentary_video=fake_render),
    )

    exit_code = main(
        [
            "run",
            "--offline",
            "--skip-tts",
            "--allow-short-render",
            "--scene-count",
            "3",
            "--duration-seconds",
            "12",
            "--date",
            "2026-06-06",
            "--output-dir",
            str(tmp_path),
        ]
    )

    metadata = json.loads((tmp_path / "metadata.json").read_text(encoding="utf-8"))

    assert exit_code == 0
    assert metadata["voice_file"] is None
    assert len(render_calls) == 1
    assert render_calls[0]["voice_path"] is None
    assert len(render_calls[0]["scene_image_paths"]) == 3
    assert render_calls[0]["music_volume"] == 0.18
    assert render_calls[0]["transition_style"] == "crossfade"


def test_tts_failure_falls_back_and_does_not_block_upload(monkeypatch, tmp_path) -> None:
    uploads: list[dict] = []

    async def fail_edge(*args, **kwargs):
        raise RuntimeError("speech.platform.bing.com failed")

    def fake_music(path, *, duration_seconds, volume=0.14):
        path.write_bytes(b"fake music")
        return path

    def fake_render(*args, **kwargs):
        kwargs["output_path"].write_bytes(b"fake video")
        assert kwargs["voice_path"] == tmp_path / "silent_voice.wav"
        return kwargs["output_path"]

    def fake_upload(video_path, **kwargs):
        uploads.append({"video_path": video_path, **kwargs})
        return "https://youtube.example/watch?v=test"

    def fake_visual_assets(plan, assets_dir, *, provider, allow_fallback):
        assets_dir.mkdir(parents=True, exist_ok=True)
        return [
            types.SimpleNamespace(path=str(assets_dir / f"scene_{scene.number:02d}.png"), to_dict=lambda scene=scene: {"scene_number": scene.number})
            for scene in plan.scenes
        ]

    monkeypatch.setattr(audio, "synthesize_voice_async", fail_edge)
    monkeypatch.setattr(audio.time, "sleep", lambda seconds: None)
    monkeypatch.setattr("youtube_daily_automation.cli.generate_background_music", fake_music)
    monkeypatch.setattr("youtube_daily_automation.cli.prepare_scene_visual_assets", fake_visual_assets)
    monkeypatch.setitem(
        sys.modules,
        "youtube_daily_automation.video",
        types.SimpleNamespace(render_documentary_video=fake_render),
    )
    monkeypatch.setitem(
        sys.modules,
        "youtube_daily_automation.upload",
        types.SimpleNamespace(upload_video=fake_upload),
    )

    exit_code = main(
        [
            "run",
            "--offline",
            "--upload",
            "--allow-short-render",
            "--scene-count",
            "3",
            "--duration-seconds",
            "12",
            "--date",
            "2026-06-06",
            "--output-dir",
            str(tmp_path),
        ]
    )

    metadata = json.loads((tmp_path / "metadata.json").read_text(encoding="utf-8"))

    assert exit_code == 0
    assert uploads[0]["video_path"] == tmp_path / "daily_documentary_2026-06-06.mp4"
    assert metadata["voice_file"] == str(tmp_path / "silent_voice.wav")
    assert metadata["youtube_url"] == "https://youtube.example/watch?v=test"
