from __future__ import annotations

import datetime as dt
import re
from dataclasses import asdict, dataclass

from .topics import InterestingTopic


@dataclass(frozen=True)
class DocumentaryScene:
    number: int
    title: str
    narration: str
    image_prompt: str
    subtitle: str
    duration_seconds: float


@dataclass(frozen=True)
class DocumentaryPlan:
    title: str
    description: str
    narration: str
    scenes: list[DocumentaryScene]
    hashtags: list[str]

    def to_dict(self) -> dict:
        return {
            "title": self.title,
            "description": self.description,
            "narration": self.narration,
            "hashtags": self.hashtags,
            "scenes": [asdict(scene) for scene in self.scenes],
        }


ARC_LABELS = (
    "Cold open",
    "The world before",
    "A quiet clue",
    "Hidden pressure",
    "The human stakes",
    "A turning point",
    "Consequences",
    "The larger pattern",
    "What changed",
    "Why it still matters",
)


def build_documentary_plan(
    *,
    topic: str,
    day: dt.date,
    source_topics: list[InterestingTopic],
    scene_count: int,
    duration_seconds: int,
    channel_name: str,
) -> DocumentaryPlan:
    if scene_count < 1:
        raise ValueError("At least one scene is required.")

    clean_topic = _clean_topic(topic)
    date_text = day.strftime("%B %d, %Y").replace(" 0", " ")
    title = f"{clean_topic}: The Story Behind the Moment"
    scene_duration = duration_seconds / scene_count
    context = _context_lines(source_topics)

    scenes = [
        _build_scene(
            number=index + 1,
            topic=clean_topic,
            context=context[index % len(context)],
            arc_label=ARC_LABELS[index % len(ARC_LABELS)],
            duration_seconds=scene_duration,
            final_scene=index == scene_count - 1,
        )
        for index in range(scene_count)
    ]
    narration = "\n\n".join(scene.narration for scene in scenes)
    hashtags = ["#Documentary", "#History", "#CinematicStory", "#DailyDocumentary"]
    description = "\n".join(
        [
            f"{channel_name} presents a cinematic documentary for {date_text}.",
            "",
            f"Topic: {clean_topic}",
            "",
            "Scene guide:",
            *[f"{scene.number:02d}. {scene.title}" for scene in scenes],
            "",
            "Generated by an automated documentary video pipeline.",
            " ".join(hashtags),
        ]
    )

    return DocumentaryPlan(
        title=title,
        description=description,
        narration=narration,
        scenes=scenes,
        hashtags=hashtags,
    )


def _build_scene(
    *,
    number: int,
    topic: str,
    context: str,
    arc_label: str,
    duration_seconds: float,
    final_scene: bool,
) -> DocumentaryScene:
    title = f"{arc_label}: {_short_title(context)}"
    narration = _scene_narration(number=number, topic=topic, context=context, arc_label=arc_label, final_scene=final_scene)
    subtitle = _subtitle_from_narration(narration)
    image_prompt = (
        "Cinematic documentary still, 16:9 widescreen, dramatic natural light, "
        f"slow camera movement implied, archival texture, realistic detail. Scene {number}: "
        f"{arc_label.lower()} for a film about {topic}. Visual focus: {context}. "
        "No text, no logos, no watermarks."
    )
    return DocumentaryScene(
        number=number,
        title=title,
        narration=narration,
        image_prompt=image_prompt,
        subtitle=subtitle,
        duration_seconds=duration_seconds,
    )


def _scene_narration(*, number: int, topic: str, context: str, arc_label: str, final_scene: bool) -> str:
    if number == 1:
        return (
            f"In every documentary, the first clue is rarely loud. In {topic}, it begins with {context}. "
            "What looks like a small detail opens a much larger question about power, memory, and consequence."
        )
    if final_scene:
        return (
            f"The story of {topic} does not end with a date or a headline. It remains in the choices people make afterward, "
            f"and in the way {context} continues to echo through the present."
        )
    return (
        f"{arc_label} reveals another layer of {topic}. {context}. "
        "Seen up close, the moment becomes less like a fact on a timeline and more like a living chain of decisions."
    )


def _context_lines(source_topics: list[InterestingTopic]) -> list[str]:
    lines = [f"{topic.title}: {topic.summary}" for topic in source_topics if topic.title and topic.summary]
    if lines:
        return lines
    return ["a forgotten event whose consequences were larger than they first appeared"]


def _clean_topic(topic: str) -> str:
    return " ".join(topic.strip().split()) or "A Hidden Story From History"


def _short_title(text: str) -> str:
    title = re.split(r"[:.!?]", text, maxsplit=1)[0]
    return " ".join(title.split()[:8]) or "Untold Evidence"


def _subtitle_from_narration(text: str) -> str:
    words = text.split()
    return " ".join(words[:18]).rstrip(",.;:") + ("..." if len(words) > 18 else "")
